export const LoginResponses = {
  LOGIN_SUCCESS: "LOGIN SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_INVALID_CREDS: "LOGIN_INVALID_CREDS",
};
export const SignUpResponses = {
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "LOGIN_FAILURE",
  SIGN_UP_UNDER_AGE_USER_FAILURE: "SIGN_UP_UNDER_AGE_USER_FAILURE",
};
export const AddCatResponses = {
  ADD_CAT_SUCCESS: "ADD_CAT_SUCCESS",
  ADD_CAT_FAILURE: "ADD_CAT_FAILURE",
};
export const ChangePwdResponses = {
  CHANGE_PWD_SUCCESS: "CHANGE_PWD_SUCCESS",
  CHANGE_PWD_FAILURE: "CHANGE_PWD_FAILURE",
  CHANGE_PWD_FAILURE_SOME_EXCEPTION: "CHANGE_PWD_FAILURE_SOME_EXCEPTION",
};
export const DeleteProductResponses = {
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",
};
export const SaveProductResponses = {
  SAVE_PRODUCT_SUCCESS: "SAVE_PRODUCT_SUCCESS",
  SAVE_PRODUCT_FAILURE: "SAVE_PRODUCT_FAILURE",
};
